version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - /app/node_modules
    environment:
      - PORT= 3030
      - NODE_ENV=production
      - VITE_APPWRITE_URL=http://93.127.194.47:7070/v1
      - VITE_APPWRITE_PROJECT=66393be000390a1c3913
